version: "3"
services:
  gootime-backend:
    image: yingyinglininin/gootime-backend:latest
    container_name: backend
    expose:
      - "4000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
    networks:
      - gootime_network
  gootime-frontend:
    image: yingyinglininin/gootime-frontend:latest
    container_name: frontend
    expose:
      - "3000"
    networks:
      - gootime_network
  # redis:
  #   image: redis
  #   container_name: redis
  #   expose:
  #     - "6379"
  #   depends_on:
  #     - gootime-backend
  #   networks:
  #     - gootime_network
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - /etc/ssl/certificate.crt:/etc/ssl/certificate.crt
      - /etc/ssl/private.key:/etc/ssl/private.key
      # - /etc/ssl/intermediate.crt:/etc/ssl/intermediate.crt
      - /etc/ssl/combined.crt:/etc/ssl/combined.crt
    depends_on:
      - gootime-backend
      - gootime-frontend
    networks:
      - gootime_network
    command: [nginx, -g, "daemon off;", "-c", "/etc/nginx/nginx.conf"]

networks:
  gootime_network:
